# Generated by Django 3.2.7 on 2021-09-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate',
            field=models.FloatField(),
        ),
    ]
