# Generated by Django 3.2.7 on 2021-09-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210903_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='gross',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rate_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
