# Generated by Django 3.2.7 on 2021-09-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210903_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gross',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
