# Generated by Django 3.2.7 on 2021-09-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
